# -- ESTÁGIO 1: CONSTRUÇÃO DA APLICAÇÃO --
# Use uma imagem com Maven e um JDK para construir o projeto
FROM maven:3.8.3-openjdk-21 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn clean package -DskipTests

# -- ESTÁGIO 2: CRIAÇÃO DA IMAGEM FINAL --
# Use uma imagem base leve para rodar a aplicação
FROM openjdk:17-jdk-slim
WORKDIR /app
# Copia o arquivo JAR do estágio de construção
COPY --from=build /app/target/*.jar app.jar
# Define o ponto de entrada para a aplicação
ENTRYPOINT ["java", "-jar", "app.jar"]